### ISSUE TITLE
No device found in intergrations

### ISSUE THREAD

**Issue by 0burner0** [lwestenberg/homeassistant_bold#1]
![image](https://user-images.githubusercontent.com/19961343/156050261-45b47a45-f95c-443d-ae0c-374a5b6f7778.png)

No device's are found.
I tried adding my main account (owner) & my secondery account specialy made for HA.
Both dont show any device's.

Remote unlock is enabled en I have the bold bridge

**Comment by lwestenberg** [comment]
I found some things that could help with solving this. Will let you know asap.

**Comment by 0burner0** [comment]
Any news?
