### ISSUE TITLE
Failed to call service

### ISSUE THREAD

**Issue by jurgen2005** [lwestenberg/homeassistant_bold#12]
The addon reports "failed to call service locl/unlock"
It does see the lock.
Does it require a bold connect?

Device info
Smart Cylinder Long Range
by Bold
Connected via [Voordeur](https://192.168.178.24:8123/config/devices/device/b00d....
Firmware: 95

**Comment by bartbakels** [comment]
Yes it does

**Comment by lwestenberg** [comment]
the integration requires a bold connect. But it is technically possible to make an integration that can work without it. I will look into that after we got the official HA integration released.

**Comment by lwestenberg** [comment]
moved to https://github.com/lwestenberg/homeassistant_bold/issues/17 as enhancement
