### ISSUE TITLE
Cannot connect (to the email) - Kan geen verbinding maken (email)

### ISSUE THREAD

**Issue by TheHesser** [lwestenberg/homeassistant_bold#14]
I have issues with registring the app with the account email I created.
It constantly says that it cannot connect (with the email provided)
I checked and the email address is correct.
![Schermafbeelding 2023-01-27 223823](https://user-images.githubusercontent.com/63908035/215205547-2016fc50-b368-4488-97c4-d9cd1092d751.png)

**Comment by tim427** [comment]
@TheHesser are you sure you are using the latest version? This looks like the first version which is not based on the new OAuth implementation.

**Comment by TheHesser** [comment]
I have uploaded the files that I downloaded 2 hours before this post.
I can try and delete all files again and upload them again?
I will keep you posted.

**Comment by lwestenberg** [comment]
this is the old version, latest version uses oAuth2 instead of an email input in the config screen
