### ISSUE TITLE
Issue with Bold Lock

### ISSUE THREAD

**Issue by quentindavid** [lwestenberg/homeassistant_bold#18]
Hi, first I would like to thank you because this integration will be really time saving :)

I don't quite understand why it's not possible to access the API locally directly on Bold Connect, it would enable the unlock operation to work offline, if internet is down...

I tested this integration using HACS, and it's very nice except when I click on "Unlock", it worked but displayed an error message `Error while locking`. 
Now the status is "unlocked", but I can't "lock" it back, when I try I get the following error:
`Échec d'appel du service lock/lock. Update the firmware of your Bold Smart Lock 'Meyrieux' to enable deactivating.`
My bold smart lock has firwmare version 95 and seems up to date. Same for the Bold connect, in version 43.

Is it normal ? What can I do ?

Thanks again for the quality of this work :)

**Comment by tim427** [comment]
Yes, currently Bold doesn's support "locking" again, which results in this error "Update your firmware".

Which is a bit misleading, because there isn't any firmware supporting that feature (yet).

Local API access doesn't exist as the Bold Connect does not provide anything like that.

**Comment by quentindavid** [comment]
I know local API does not exist at the moment, but it would be so nice ! I like to have real control over the things I buy...because now we rely on the existence of Bold services on the cloud...If it's gone we can't unlock.

Regarding the software, do you think it will be supporting the feature soon ? If not, would it be possible to implement "unlock only" mechanism in order to avoid error ?

**Comment by quentindavid** [comment]
If not, maybe we could simply use the "button" integration instead of "lock", because we don't have the state of the lock, and we can only do one action basically, which is ask to unlock, isn't it ?

By the way thanks again a lot for your work :)

**Comment by lwestenberg** [comment]
I'm thinking about opening a HA feature request for locks that only support unlocking. This will probably take some time to get. Button would be a functional solution but also kind of weird since it should be an entity of type lock (it is a lock).

Meanwhile we will be working with Bold also to implement locking. I don't expect that they will release a local API since everything is checked (access rules etc.) and signed via their server.

**Comment by quentindavid** [comment]
Agreed. I already ask for this feature to Bold directly several times by e-mail. You can do the same as well :) But I'm not sure they will take this into consideration. It is quite frustrating they don't implement new features over time, and it's very cool that you were able to fill that gap with home assistant integration. But it should be done by Bold I think !
Or at least they should give us the means to work...

Regarding HA lock entity, I agree too, I think it's the entity that must be updated to take in consideration locks that only unlocks and then lock itself back after some time... I would "+1" if you ask for this :)

**Comment by quentindavid** [comment]
FYI I created a script in order to call unlock service. It allow to create a dedicated tile on top of the notification bar of android, very practical mean to unlock the door.
Again, Bold app should give us this basic feature ! Or a widget I don't know...

**Comment by tim427** [comment]
Yeah, I do the same with the HA Badges:
```
      - entity: lock.front_door
        tap_action:
          action: call-service
          service: lock.unlock
          service_data:
            entity_id: lock.front_door
```

I'm in close contact with one of the developers of Bold during the test phase and they are also really excited for this HA integration and they told me "we currently don't have firmware available to do so and I can't say when this will be available".

**Comment by quentindavid** [comment]
yes firmware has not been upgrade since almost 1 year, when I bought the Bold smart lock. For me this is disapointing !
Thanks for the tip with the badges.

Maybe they should have a look at the "matter" protocol. I think it imposes a local connection to the things.

**Comment by tim427** [comment]
Besides this specific "lock"-feature, what do you expect?

I mean, no updates for a full featured device, such as a smartphone or a computer, that's indeed disappointing. But a device that can only "activate" and "deactivate" a outside turning knob; what would you expect more?

Matter is a protocol and probably to big to load on these specifically designed Bold Smart Locks, same for the Bold Connect, which is just a basic ESP32 and "bridging" the messages from the API/Cloud over Bluetooth. All the cryptographic thingies are done by Bold.

**Comment by quentindavid** [comment]
For example as you said, being able to isolate activate and deactivate function. Or having a status sent back to the app in order to be sure the door is locked or unlocked ?
The button located on the Bold Connect could also be used to unlock the door (and I could solder a transistor in order to activate my lock directly :)

Regarding Matter, I don't know the details but I hope it can be implemented using an ESP32. It has BLE, WiFi and plenty of memory...But if they are not able to update the firmware to add some fancy features, they will surely not add Matter's compatibility.

**Comment by tim427** [comment]
> .. The button located on the Bold Connect could also be used to unlock the door (and I could solder a transistor in order to activate my lock directly
You meant the Bold Clicker right? Which is different approach, the clicker always works, and the App checks live whether or not it’s allowed to do so. With this approach it’s possible to revoke someone’s access and/or on specific times/days, etc.

**Comment by quentindavid** [comment]
> > .. The button located on the Bold Connect could also be used to unlock the door (and I could solder a transistor in order to activate my lock directly
> 
> You meant the Bold Clicker right? Which is different approach, the clicker always works, and the App checks live whether or not it’s allowed to do so. With this approach it’s possible to revoke someone’s access and/or on specific times/days, etc.
No there is a button on the bold connect and this one is pretty much useless ^^ It could allow some features...
> 
> Besides that, the only way to have long(er) battery lifespan; keep the lock as simple as possible. The Bold Connect on the other hand; this _could_ be local interfacing, and therefore a "always allowed" user. But I could imagine this isn't allowed, purely because Bold can't verify the access and therefore not guarantee the safety ;)
I understand but on my point of view, people should be free to manage their safety. If they allow the Bold Connect to act as a key with local interface (protected using token, user/password and so on ), it's their choice...

**Comment by tim427** [comment]
> > > .. The button located on the Bold Connect could also be used to unlock the door (and I could solder a transistor in order to activate my lock directly
> > 
> > 
> > You meant the Bold Clicker right? Which is different approach, the clicker always works, and the App checks live whether or not it’s allowed to do so. With this approach it’s possible to revoke someone’s access and/or on specific times/days, etc.
> 
> No there is a button on the bold connect and this one is pretty much useless ^^ It could allow some features...
> 
Are you sure you understand the product? Have you read the manual? That button triggers the "Bold Controller" function of that specific Bold Connect -> The relais function.
![image](https://user-images.githubusercontent.com/4570297/216284180-f1cb3d3e-e3f8-45be-b570-5618a4348c1d.png)
> > Besides that, the only way to have long(er) battery lifespan; keep the lock as simple as possible. The Bold Connect on the other hand; this _could_ be local interfacing, and therefore a "always allowed" user. But I could imagine this isn't allowed, purely because Bold can't verify the access and therefore not guarantee the safety ;)
> 
> I understand but on my point of view, people should be free to manage their safety. If they allow the Bold Connect to act as a key with local interface (protected using token, user/password and so on ), it's their choice...

I don't think that any certification company agrees with you..

**Comment by quentindavid** [comment]
I didn't you you can activate the relay with the button, ok nice to have but in my case I won't use this feature.

Regarding the "certification company", I don't understand. Is it more secure that the list of people allowed to open my door is stored somewhere lost in the cloud, somewhere I don't manage, I can't check if it's managed in a secure way ? Instead of being able to manage it locally, on my own, and on my premises ??

**Comment by lwestenberg** [comment]
an example of how to use it currently:

`
type: tile
entity: lock.my_door
tap_action:
  action: call-service
  service: lock.unlock
  target:
    entity_id: lock.my_door
  data: {}
`
