### ISSUE TITLE
Getting OAuth failure

### ISSUE THREAD

**Issue by bastichelaar** [lwestenberg/homeassistant_bold#19]
I can't get this to work. Maybe I'm missing something here. I added the custom_componentvia HACS. When adding the integration, Home Assistant asks me to enter the OAuth credentials manually, but I don't have them. When entering dummy values, it and click on save, it opens the page or the app, asking me to link the application. When I press "Yes link" it gives me the error Oauth Failure. Debugging this in the browser gives me the following:

```
error: "invalid_request"
errorMessage: "OAuth failure"
error_description: "RedirectUriInvalid"
message: "OAuth failure"
```
The URL (in the browser) is https://auth.boldsmartlock.com/?response_type=code&client_id=BoldAuth&redirect_uri=https://my.home-assistant.io/redirect/oauth&state=...

What am I missing here?

**Comment by lwestenberg** [comment]
issue was fixed with the latest version
