### ISSUE TITLE
not connection issue in homeassistant

### ISSUE THREAD

**Issue by ashobgame** [lwestenberg/homeassistant_bold#2]
This error originated from a custom integration.

Logger: custom_components.bold.coordinator
Source: custom_components/bold/coordinator.py:87
Integration: Bold
First occurred: 7:35:11 PM (2 occurrences)
Last logged: 7:35:25 PM

Cannot connect

**Comment by lwestenberg** [comment]
Thanks for reporting, looks like something changed in the API and I'm able to reproduce the issue. I'm looking into it.

**Comment by lwestenberg** [comment]
Seems that Bold is also having issues. Turn off Bluetooth on your phone and try remote activation with the Bold app. It gives a timeout. I checked the latest app and all server calls still seem to be the same (with X-Auth-Token). I contacted Bold about the issue.

**Comment by michelmolleman** [comment]
Is there a solution available. I have the same problem …

**Comment by lwestenberg** [comment]
We're working on releasing an official HA integration and have arranged everything officially now with Bold. For now I will close this issue, please check the Core repo on my GitHub to see the latest progress before merging.

**Comment by Gnol86** [comment]
Thanks you for the job. Do you have an estimate of when the official integration will be released?

**Comment by lwestenberg** [comment]
it can be used as custom_component now from this repo source.

**Comment by peetersit** [comment]
It worked right away. Without hassle. This is awesome!!! Keep up the good work…Thanks Patrick
