### ISSUE TITLE
Integration fails with error communicating with api

### ISSUE THREAD

**Issue by bartbakels** [lwestenberg/homeassistant_bold#21]
As of last friday the integration fails with the error that it cannot communicate with the api.

im on 2023.5.4

**Comment by FutureCow** [comment]
Got the same error. After deleting and adding the lock I got this error from nabu casa:


> Oops... an error occured
> Unexpected response Too Many Requests

**Comment by plasterer41** [comment]
Same problem as @FutureCow

**Comment by plasterer41** [comment]
Was working fine for a couple of months.

**Comment by callumeveratt** [comment]
+1, also started getting this today

**Comment by rwanrooy** [comment]
This happened last week here also. I was able to add the integration again and use it for a week but now I get the "too many requests" at the Nabu Casa site also.

**Comment by plasterer41** [comment]
I added the locks to Google Home and added Google Home SDK into my home assistant and reintegrated the locks that way. Works great now.

**Comment by plasterer41** [comment]
https://youtu.be/a-Is8GtLJCs

**Comment by callumeveratt** [comment]
Working again today - was able to readd. API was maybe down?

**Comment by plasterer41** [comment]
Yes, worked again for me too. I kept the google home automation also just in case it goes down again.

**Comment by Gnol86** [comment]
#22 It's fix !! Thank you

**Comment by schoutendn** [comment]
I'm still running into this error using HA version 2023.7.1 and the latest version of the integration.

**Comment by lwestenberg** [comment]
just did an update that fixes the setup errors. All should be working again.
