### ISSUE TITLE
Installation OAuth not working

### ISSUE THREAD

**Issue by ReneReneB** [lwestenberg/homeassistant_bold#30]
Hello everyone,

I had already installed the integration. However, the lock has not been supported for the last 2 weeks.

I have therefore decided to delete the integration and reinstall it.

However, I encountered a problem with the OAUth verification. Unfortunately, there are no instructions in the documentation on how to proceed. What do I have to do here?

![Bold 2](https://github.com/lwestenberg/homeassistant_bold/assets/152493847/d876b230-a039-44d7-a590-38a53a84c5c1)
![Bold 1](https://github.com/lwestenberg/homeassistant_bold/assets/152493847/5caaf35a-2d5f-452f-b91e-cb7fd8badc39)

Thanks and best regards René

**Comment by tim427** [comment]
@ReneReneB could you try to login from a full desktop browser?

My guess, the Bold App, is opening the OAuth request and is handled differently in comparison with the normal OAuth flow.

**Comment by ReneReneB** [comment]
I tried the desktop browser first. I was redirected to the Bold website, entered my email, password and the pin sent to me. But I got an error message there too

**Comment by tim427** [comment]
More info regarding the "an error message"? Screenshot?

**Comment by ReneReneB** [comment]
thats the link to the bold website: https://auth.boldsmartlock.com/verify/email?mode=login
![image](https://github.com/lwestenberg/homeassistant_bold/assets/152493847/62e9429d-1c56-459b-afc3-c55dc5969645)

**Comment by tim427** [comment]
@ReneReneB are you 100% sure you are using this OAuth flow, starting with HomeAssistant??

I've just tested it, multiple times, and it works flawless.

I'm highly in doubt, because your URL contains `client_id=Bold+OAuth` -> this integration uses a different `client_id=HomeAssistant`...

On this stage, I would expect something like; `https://auth.boldsmartlock.com/integration?client_id=HomeAssistant&response_type=code&redirect_uri=https%3A%2F%2Faccount-link.nabucasa.com%2Fauthorize_callback&state=<CUT>`

**Comment by ReneReneB** [comment]
no I´m not 100% sure that I´m using the correct OAuth flow. I did not find any instructions and tried to make it myself.
In the first step, I added new application credentials:
![image](https://github.com/lwestenberg/homeassistant_bold/assets/152493847/111203a0-1c8c-4acd-b2ea-0c77f884e7a8)
![image](https://github.com/lwestenberg/homeassistant_bold/assets/152493847/ad2c3b2d-756a-43f5-beaf-84e06838234d)

Integration: Bold
OAuth Client ID: self-created text
OAuth Client ID: self-created text

I entered this information in the login window under “Add integration”

**Comment by tim427** [comment]
You are trying to add manually "Application credentials"?

That's not the way...

Please, just add "Bold" as an integration (After you've installed the integation via HACS or manually adding `bold` to the `config/custom_components/` folder), by pressing that big blue button "Integation Hinzufugen", find Bold and follow the steps.

**Comment by ReneReneB** [comment]
But what do I have to enter here?
![image](https://github.com/lwestenberg/homeassistant_bold/assets/152493847/30199e5c-16ae-428f-8552-073f34514aa2)
I don't know what OAuth Client ID and OAuth Client Secret is and what I should insert

**Comment by ReneReneB** [comment]
I have not only restarted Home Assistant but also my PC. The login page looked different now. For whatever reason. But I was able to install the integration successfully.
