### ISSUE TITLE
No error messages, but lock does not switch via the Connect

### ISSUE THREAD

**Issue by rtrinks** [lwestenberg/homeassistant_bold#4]
Was able to add the configuration without any problems.
Home Assistant restarted
Created an account in the Bol app and that it can activate remotely
Application added
New account email address used
Code in the mail and associated password used.
Entity is well added and looks good.

Can now click the option click and also works without errors, but nothing happens with door lock.

How can I fix this, am I doing something wrong?

**Comment by rtrinks** [comment]
I contacted Bold Smart Lock by phone and they said it worked with Home Assistant before.
Since they had to move everything, there have been changes. They also just release documentation for that.

Is there a possibility that a solution will be found to make Bold Smart Lock work again in Home Assistant?

**Comment by tim427** [comment]
Hi @rtrinks ,

Yeah, they changed the authentication part to OAuth, where the authentication-flow, has to be "approved" by opening a link on your phone, which opens that specific link with the Bold-app.

Once there is a valid authenticated session, the rest will be fairly easy to implement.

Where did you find the documentation -> this will help a lot :)
