### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by x2fzhl** [lwestenberg/homeassistant_bold#5]
When trying to provide my bold email account, I get stuck with this:

Logger: custom_components.bold.config_flow
Source: custom_components/bold/config_flow.py:75
Integration: Bold
First occurred: October 11, 2022 at 9:15:16 PM (3 occurrences)
Last logged: 8:53:13 AM

**Comment by WesleyNahuijsen** [comment]
Zelfde probleem hier:

Logger: custom_components.bold.config_flow
Source: custom_components/bold/config_flow.py:75
Integration: Bold
First occurred: 19 oktober 2022 om 21:41:07 (4 occurrences)
Last logged: 09:56:57

Cannot connect

**Comment by lwestenberg** [comment]
A rewrite that fixes it all and implements the latest API is coming soon

**Comment by WesleyNahuijsen** [comment]
Thanks, when can we expect the update

**Comment by tim427** [comment]
> Thanks, when can we expect the update?

Currently we're testing the last parts and polishing the documentation, with as endgoal; an official HA integration :)

**Comment by koenieee** [comment]
Nice, that's great news :)
I was already using my own implementation, but during the 0Auth, now they need they key works a little bit different

**Comment by lwestenberg** [comment]
For now you can test the current work with the Core repo fork on my GitHub. Will close this issue for now.

**Comment by lwestenberg** [comment]
oauth version is also updated in this repo now, to avoid people using the outdated code
