### ISSUE TITLE
request_validation_id() missing?

### ISSUE THREAD

**Issue by titom43** [lwestenberg/homeassistant_bold#6]
Hello,

Not sure if it is on my side but I raise "cannot_connect" error.

Investigating, I can't find the "request_validation_id" function.
I can't either find any references to bold URLs (I expect to see https://api.sesamtechnology.com/v2/xxx somewhere...).

Is there any file missing in the git repo?

Best regards,
Thomas

**Comment by lwestenberg** [comment]
Hi, we are switching to the oAuth2 login (take a look at my fork of Core) and releasing it as an official Addon for HA so this whole validation_id thing is deprecated.

**Comment by lwestenberg** [comment]
oauth version source is added to this repo for now.
